/**
 * SEND PAYMENT RECEIPT EMAIL
 * Sends payment confirmation/receipt to customer
 * 
 * @version 1.0.0
 * @date December 27, 2025
 */

import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: NextRequest) {
  try {
    const { invoiceId, to, amount, invoiceNumber, businessName, currency = 'USD' } = await request.json();

    if (!to || !amount || !invoiceNumber) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const currencySymbols: Record<string, string> = {
      USD: '$', EUR: '€', GBP: '£', CAD: 'C$', AUD: 'A$'
    };
    const symbol = currencySymbols[currency] || '$';
    const formattedAmount = `${symbol}${amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
    const paidDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    });

    const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #10b981, #059669); color: white; padding: 40px; border-radius: 12px 12px 0 0; text-align: center; }
    .checkmark { font-size: 64px; margin-bottom: 15px; }
    .content { background: #fff; padding: 30px; border: 1px solid #e5e7eb; }
    .receipt-box { background: #f0fdf4; border: 2px solid #10b981; border-radius: 12px; padding: 25px; margin: 20px 0; text-align: center; }
    .amount { font-size: 42px; font-weight: bold; color: #059669; }
    .details { background: #f9fafb; padding: 20px; border-radius: 8px; margin-top: 20px; }
    .row { padding: 10px 0; border-bottom: 1px solid #e5e7eb; }
    .row:last-child { border-bottom: none; }
    .label { color: #6b7280; }
    .value { font-weight: 600; float: right; }
    .footer { text-align: center; padding: 25px; color: #6b7280; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="checkmark">✓</div>
      <h1 style="margin:0;">Payment Received!</h1>
      <p style="margin:10px 0 0;opacity:0.9;">Thank you for your payment</p>
    </div>
    <div class="content">
      <div class="receipt-box">
        <p style="margin:0;color:#6b7280;font-size:14px;">Amount Paid</p>
        <p class="amount">${formattedAmount}</p>
        <p style="margin:0;color:#059669;font-weight:600;">Payment Successful</p>
      </div>
      <div class="details">
        <div class="row">
          <span class="label">Invoice Number</span>
          <span class="value">${invoiceNumber}</span>
        </div>
        <div class="row">
          <span class="label">From</span>
          <span class="value">${businessName || 'Business'}</span>
        </div>
        <div class="row">
          <span class="label">Payment Date</span>
          <span class="value">${paidDate}</span>
        </div>
        <div class="row">
          <span class="label">Status</span>
          <span class="value" style="color:#059669;">PAID</span>
        </div>
      </div>
      <p style="margin-top:25px;text-align:center;color:#6b7280;">
        This receipt confirms your payment has been processed successfully.
        Please keep this email for your records.
      </p>
    </div>
    <div class="footer">
      <p>Receipt generated by Invoice Generator Pro</p>
      <p>Powered by CR AudioViz AI</p>
    </div>
  </div>
</body>
</html>`;

    const { data, error } = await resend.emails.send({
      from: 'Invoice Generator <receipts@craudiovizai.com>',
      to: [to],
      subject: `Payment Receipt - Invoice ${invoiceNumber}`,
      html: html
    });

    if (error) throw new Error(error.message);

    return NextResponse.json({ success: true, messageId: data?.id });
  } catch (error: any) {
    console.error('Receipt email error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
